# JP2Forge Web Docker Compose Configuration
# Version: 0.1.3 (May 6, 2025)
#
# This docker-compose file defines the services needed to run JP2Forge Web in Docker.
# V0.1.3 improvements:
# - Removed obsolete version attribute
# - Added proper container healthchecks for all services
# - Improved service dependency chain
# - Enhanced volume management with named volumes
# - Better container naming and environment variable handling
# - Added restart policies for production reliability

services:
  # PostgreSQL Database
  db:
    image: postgres:13
    container_name: jp2forge_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-jp2forge}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-jp2forge_password}
      - POSTGRES_DB=${POSTGRES_DB:-jp2forge}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-jp2forge}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Redis for Celery
  redis:
    image: redis:6
    container_name: jp2forge_redis
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    ports:
      - "6379:6379"

  # Django Web Application
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: jp2forge_web
    container_name: jp2forge_web
    volumes:
      - ./:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CREATE_SUPERUSER=true
    ports:
      - "8000:8000"
    restart: unless-stopped

  # Celery Worker for Background Tasks
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: jp2forge_celery
    container_name: jp2forge_worker
    command: celery -A jp2forge_web worker -l INFO --concurrency=2
    volumes:
      - ./:/app
      - media_volume:/app/media
    depends_on:
      - web
      - redis
      - db
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:
