# Generated by Django 4.2 on 2025-04-28 13:25

import converter.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversionJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "original_file",
                    models.FileField(upload_to=converter.models.job_directory_path),
                ),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "output_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "result_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=converter.models.job_directory_path,
                    ),
                ),
                (
                    "compression_mode",
                    models.CharField(
                        choices=[
                            ("lossless", "Lossless"),
                            ("lossy", "Lossy"),
                            ("supervised", "Supervised"),
                            ("bnf_compliant", "BnF Compliant"),
                        ],
                        default="supervised",
                        max_length=20,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("photograph", "Photograph"),
                            ("heritage_document", "Heritage Document"),
                            ("color", "Color"),
                            ("grayscale", "Grayscale"),
                        ],
                        default="photograph",
                        max_length=20,
                    ),
                ),
                ("bnf_compliant", models.BooleanField(default=False)),
                ("quality", models.FloatField(default=40.0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("progress", models.FloatField(default=0)),
                ("task_id", models.CharField(blank=True, max_length=255, null=True)),
                ("original_size", models.BigIntegerField(blank=True, null=True)),
                ("converted_size", models.BigIntegerField(blank=True, null=True)),
                ("compression_ratio", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversion_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
