# Generated by Django 5.2.3 on 2025-06-20 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("converter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversionjob",
            name="enable_expert_mode",
            field=models.BooleanField(default=False),
        ),
    ]
