name: Docker

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]

jobs:
  build-test:
    name: Build & Test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        load: true
        tags: jp2forge_web:test
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Test Docker image
      run: |
        # Test basic Docker image
        docker run --rm jp2forge_web:test python manage.py check --settings=jp2forge_web.settings