name: Security

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '0 6 * * 1'  # Weekly on Monday

jobs:
  dependency-check:
    name: Dependency Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install safety bandit
        pip install -r requirements.txt
    
    - name: Run Safety (dependency vulnerabilities)
      run: |
        safety check --json --output safety-report.json || true
        safety check
    
    - name: Run Bandit (code security)
      run: |
        bandit -r . -f json -o bandit-report.json || true
        bandit -r . --skip B101,B104,B107,B108,B311,B404,B601,B602,B603,B607
    
    - name: Upload security reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-reports
        path: |
          safety-report.json
          bandit-report.json